openapi: 3.0.0
info:
  title: data types related to organizations (beta)
  version: v1beta
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
components:
  schemas:
    VatNumber:
      description: An international Value-Added Tax Identification Number or VAT Identification Number (VATIN)
      type: string
      pattern: "^[A-Z]{2}.+$" # Starts with ISO 3166-1 alpha-2 country code, followed by 1 or more characters in a country-specific format